export async function generateDocumentation(idea, components, pinAssignments) {
  const componentList = components.map(c =>
    c.name + ' (' + c.category + ')'
  ).join(', ')

  const pinList = pinAssignments && pinAssignments.length > 0
    ? pinAssignments.map(p =>
        p.componentName + ' ' + p.componentPin + ' → ' + p.mcuPin
      ).join(', ')
    : 'No pin assignments defined'

  const settings = localStorage.getItem('protomind_settings')
  const model = settings ? (JSON.parse(settings).aiModel || 'llama3.2') : 'llama3.2'
  const ollamaUrl = settings ? (JSON.parse(settings).ollamaUrl || 'http://localhost:11434') : 'http://localhost:11434'

  const response = await fetch(ollamaUrl + '/api/generate', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model,
      prompt: 'You are a technical writer. Generate complete technical documentation for this electronics prototype.\n\nIdea: "' + idea + '"\nComponents: ' + componentList + '\nPin connections: ' + pinList + '\n\nReply ONLY with this exact JSON:\n\n{"title": "Project Title", "version": "1.0.0", "overview": "2-3 sentences describing the project", "features": ["Feature 1", "Feature 2"], "requirements": {"hardware": ["Arduino Nano", "USB cable"], "software": ["Arduino IDE 2.0+", "DHT library"]}, "gettingStarted": ["Step 1: Install Arduino IDE", "Step 2: Install required libraries", "Step 3: Connect components per wiring diagram"], "wiringGuide": [{"from": "Arduino 5V", "to": "DHT22 VCC", "color": "red", "notes": "Power supply"}], "codeDocumentation": {"globalVariables": ["int sensorPin = 2; // Sensor data pin"], "setupFunction": "Initializes serial communication and pin modes", "loopFunction": "Reads sensor every 2 seconds and prints to Serial"}, "troubleshooting": [{"problem": "Sensor not reading", "cause": "Loose connection", "solution": "Check all wire connections"}], "safetyNotes": ["Do not exceed 5V", "Check polarity before powering on"], "futureImprovements": ["Add WiFi connectivity", "Add LCD display"], "license": "MIT", "author": "ProtoMind Builder"}',
      stream: false,
    }),
  })

  const data = await response.json()
  const text = data.response
  const jsonMatch = text.match(/\{[\s\S]*\}/)
  if (!jsonMatch) throw new Error('No JSON found')
  return JSON.parse(jsonMatch[0])
}

export function generateMarkdown(doc, idea, components) {
  const lines = [
    '# ' + (doc.title || idea),
    '',
    '> Version ' + (doc.version || '1.0.0') + ' | Generated by ProtoMind',
    '',
    '## Overview',
    '',
    doc.overview || '',
    '',
    '## Features',
    '',
    ...(doc.features || []).map(f => '- ' + f),
    '',
    '## Components',
    '',
    ...components.map(c => '- **' + c.name + '** (' + c.category + ')'),
    '',
    '## Requirements',
    '',
    '### Hardware',
    ...(doc.requirements?.hardware || []).map(h => '- ' + h),
    '',
    '### Software',
    ...(doc.requirements?.software || []).map(s => '- ' + s),
    '',
    '## Getting Started',
    '',
    ...(doc.gettingStarted || []).map((step, i) => (i + 1) + '. ' + step),
    '',
    '## Wiring Guide',
    '',
    '| From | To | Wire Color | Notes |',
    '|------|-----|-----------|-------|',
    ...(doc.wiringGuide || []).map(w =>
      '| ' + w.from + ' | ' + w.to + ' | ' + (w.color || 'N/A') + ' | ' + (w.notes || '') + ' |'
    ),
    '',
    '## Code Documentation',
    '',
    '### Global Variables',
    '',
    '```cpp',
    ...(doc.codeDocumentation?.globalVariables || []),
    '```',
    '',
    '### setup()',
    '',
    doc.codeDocumentation?.setupFunction || '',
    '',
    '### loop()',
    '',
    doc.codeDocumentation?.loopFunction || '',
    '',
    '## Troubleshooting',
    '',
    ...(doc.troubleshooting || []).map(t => [
      '### ' + t.problem,
      '**Cause:** ' + t.cause,
      '**Solution:** ' + t.solution,
      '',
    ].join('\n')),
    '## Safety Notes',
    '',
    ...(doc.safetyNotes || []).map(s => '> ⚠️ ' + s),
    '',
    '## Future Improvements',
    '',
    ...(doc.futureImprovements || []).map(f => '- [ ] ' + f),
    '',
    '---',
    '',
    '**License:** ' + (doc.license || 'MIT'),
    '',
    '*Generated with ProtoMind — protomind-ten.vercel.app*',
  ]
  return lines.join('\n')
}