export async function generateEnclosureSpec(idea, components, options) {
  const componentList = components.map(function(c) {
    return c.name + ' (' + c.category + ')'
  }).join(', ')

  const settings = localStorage.getItem('protomind_settings')
  const model = settings ? (JSON.parse(settings).aiModel || 'llama3.2') : 'llama3.2'
  const ollamaUrl = settings ? (JSON.parse(settings).ollamaUrl || 'http://localhost:11434') : 'http://localhost:11434'

  const prompt = [
    'You are an expert mechanical engineer specialising in electronics enclosures.',
    'Generate detailed enclosure specifications for this prototype.',
    'Prototype: ' + idea,
    'Components: ' + componentList,
    'Enclosure type: ' + (options.type || 'Desktop'),
    'Material: ' + (options.material || 'PLA'),
    'Reply ONLY with valid JSON with exactly these keys:',
    'enclosureName (string),',
    'type (string),',
    'outerDimensions (object with: length, width, height, unit),',
    'wallThickness (string),',
    'material (string),',
    'printSettings (object with: layerHeight, infill, supports, printTime, filamentUsage),',
    'features (array of objects with: name, description, location, dimensions),',
    'cutouts (array of objects with: name, shape, width, height, location, component),',
    'mountingHoles (array of objects with: diameter, x, y, notes),',
    'ventilation (object with: required, type, count, size, location),',
    'assembly (array of strings, assembly steps),',
    'tips (array of strings),',
    'alternativeMaterials (array of objects with: material, pros, cons, bestFor)',
  ].join('\n')

  const response = await fetch(ollamaUrl + '/api/generate', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ model, prompt, stream: false }),
  })

  const data = await response.json()
  const text = data.response
  const jsonMatch = text.match(/\{[\s\S]*\}/)
  if (!jsonMatch) throw new Error('No JSON found')
  return JSON.parse(jsonMatch[0])
}

export function exportEnclosureSpec(spec, idea) {
  const lines = [
    'ENCLOSURE SPECIFICATION: ' + (spec.enclosureName || idea),
    '='.repeat(60),
    '',
    'TYPE: ' + (spec.type || 'Desktop'),
    'MATERIAL: ' + (spec.material || 'PLA'),
    '',
    'DIMENSIONS',
    '-'.repeat(40),
    'Length: ' + (spec.outerDimensions?.length || 'N/A') + ' ' + (spec.outerDimensions?.unit || 'mm'),
    'Width: ' + (spec.outerDimensions?.width || 'N/A') + ' ' + (spec.outerDimensions?.unit || 'mm'),
    'Height: ' + (spec.outerDimensions?.height || 'N/A') + ' ' + (spec.outerDimensions?.unit || 'mm'),
    'Wall Thickness: ' + (spec.wallThickness || 'N/A'),
    '',
    '3D PRINT SETTINGS',
    '-'.repeat(40),
    'Layer Height: ' + (spec.printSettings?.layerHeight || 'N/A'),
    'Infill: ' + (spec.printSettings?.infill || 'N/A'),
    'Supports: ' + (spec.printSettings?.supports || 'N/A'),
    'Print Time: ' + (spec.printSettings?.printTime || 'N/A'),
    'Filament: ' + (spec.printSettings?.filamentUsage || 'N/A'),
    '',
    'CUTOUTS',
    '-'.repeat(40),
    (spec.cutouts || []).map(function(c) {
      return c.name + ': ' + c.width + 'x' + c.height + ' (' + c.location + ')'
    }).join('\n'),
    '',
    'ASSEMBLY STEPS',
    '-'.repeat(40),
    (spec.assembly || []).map(function(s, i) { return (i + 1) + '. ' + s }).join('\n'),
    '',
    '---',
    'Generated by ProtoMind — protomind-ten.vercel.app',
  ]

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = 'Enclosure_' + (idea || 'spec').replace(/[^a-zA-Z0-9]/g, '_').slice(0, 20) + '.txt'
  link.click()
  URL.revokeObjectURL(url)
}