import jsPDF from 'jspdf'

const CATEGORY_COLORS_RGB = {
  Microcontroller: [99, 102, 241],
  Sensor: [14, 165, 233],
  Display: [34, 197, 94],
  Communication: [239, 68, 68],
  Power: [245, 158, 11],
  Actuator: [168, 85, 247],
  Module: [100, 116, 139],
  Memory: [100, 116, 139],
}

export function generatePrototypePDF(idea, components, validation) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()

  // ── COVER PAGE ──────────────────────────────────────
  doc.setFillColor(10, 10, 15)
  doc.rect(0, 0, pageWidth, pageHeight, 'F')
  doc.setFillColor(99, 102, 241)
  doc.rect(0, 0, pageWidth, 3, 'F')

  doc.setTextColor(99, 102, 241)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('ProtoMind', 20, 25)

  doc.setTextColor(100, 116, 139)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('Prototype Report - ' + new Date().toLocaleDateString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric'
  }), pageWidth - 20, 25, { align: 'right' })

  doc.setDrawColor(30, 30, 46)
  doc.line(20, 30, pageWidth - 20, 30)

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(28)
  doc.setFont('helvetica', 'bold')
  doc.text('Prototype Report', 20, 70)

  doc.setTextColor(165, 180, 252)
  doc.setFontSize(13)
  doc.setFont('helvetica', 'italic')
  const ideaLines = doc.splitTextToSize('"' + idea + '"', pageWidth - 40)
  doc.text(ideaLines, 20, 90)

  const statsY = 130
  const boxW = 50
  const stats = [
    { label: 'Components', value: String(components.length) },
    { label: 'Est. Min Cost', value: '$' + String(components.length * 2) },
    { label: 'Est. Max Cost', value: '$' + String(components.length * 20) },
  ]

  stats.forEach((stat, i) => {
    const x = 20 + i * (boxW + 10)
    doc.setFillColor(13, 13, 26)
    doc.roundedRect(x, statsY, boxW, 30, 3, 3, 'F')
    doc.setDrawColor(30, 30, 46)
    doc.roundedRect(x, statsY, boxW, 30, 3, 3, 'S')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text(stat.value, x + boxW / 2, statsY + 14, { align: 'center' })
    doc.setTextColor(100, 116, 139)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.text(stat.label, x + boxW / 2, statsY + 24, { align: 'center' })
  })

  if (validation) {
    const scoreColor = validation.score >= 80 ? [34, 197, 94] : validation.score >= 60 ? [245, 158, 11] : [239, 68, 68]
    const x = 20 + 3 * (boxW + 10)
    doc.setFillColor(13, 13, 26)
    doc.roundedRect(x, statsY, boxW, 30, 3, 3, 'F')
    doc.setTextColor(...scoreColor)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text(validation.score + '/100', x + boxW / 2, statsY + 14, { align: 'center' })
    doc.setTextColor(100, 116, 139)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.text('AI Score', x + boxW / 2, statsY + 24, { align: 'center' })
  }

  doc.setTextColor(30, 30, 46)
  doc.setFontSize(8)
  doc.text('Generated by ProtoMind - AI Prototype Generator', pageWidth / 2, pageHeight - 15, { align: 'center' })

  // ── PAGE 2 — COMPONENTS ─────────────────────────────
  doc.addPage()
  doc.setFillColor(10, 10, 15)
  doc.rect(0, 0, pageWidth, pageHeight, 'F')
  doc.setFillColor(99, 102, 241)
  doc.rect(0, 0, pageWidth, 3, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('Components List', 20, 22)

  doc.setTextColor(100, 116, 139)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(components.length + ' components selected', 20, 30)

  // Manual table header
  let tY = 40
  const cols = [10, 55, 35, 15, 25, 50]
  const headers = ['#', 'Component', 'Category', 'Qty', 'Price', 'Purpose']

  doc.setFillColor(30, 30, 46)
  doc.rect(18, tY - 5, pageWidth - 36, 10, 'F')
  doc.setTextColor(165, 180, 252)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')

  let cx = 20
  headers.forEach((h, i) => {
    doc.text(h, cx, tY)
    cx += cols[i]
  })
  tY += 8

  // Table rows
  components.forEach((comp, idx) => {
    if (tY > pageHeight - 20) {
      doc.addPage()
      doc.setFillColor(10, 10, 15)
      doc.rect(0, 0, pageWidth, pageHeight, 'F')
      tY = 20
    }

    doc.setFillColor(idx % 2 === 0 ? 13 : 15, idx % 2 === 0 ? 13 : 15, idx % 2 === 0 ? 26 : 20)
    doc.rect(18, tY - 5, pageWidth - 36, 9, 'F')

    doc.setTextColor(255, 255, 255)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')

    const reason = comp.reason
      ? comp.reason.slice(0, 30) + (comp.reason.length > 30 ? '...' : '')
      : ''

    const row = [
      String(idx + 1),
      comp.name.slice(0, 20) + (comp.name.length > 20 ? '...' : ''),
      comp.category,
      String(comp.quantity || 1),
      '$2-$20',
      reason,
    ]

    cx = 20
    row.forEach((cell, i) => {
      doc.text(cell, cx, tY)
      cx += cols[i]
    })
    tY += 9
  })

  // ── PAGE 3 — WIRING GUIDE ───────────────────────────
  doc.addPage()
  doc.setFillColor(10, 10, 15)
  doc.rect(0, 0, pageWidth, pageHeight, 'F')
  doc.setFillColor(99, 102, 241)
  doc.rect(0, 0, pageWidth, 3, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('Wiring Guide', 20, 22)

  const WIRING = {
    Microcontroller: ['Connect VCC to 3.3V or 5V power rail', 'Connect GND to ground rail', 'Use GPIO pins for sensor data lines', 'Use I2C (SDA/SCL) for displays'],
    Sensor: ['Connect VCC to 3.3V (check datasheet)', 'Connect GND to common ground', 'Connect DATA/OUT pin to GPIO', 'Add 10k pull-up resistor if required'],
    Display: ['Connect VCC to 3.3V', 'Connect GND to ground', 'SDA to I2C data pin', 'SCL to I2C clock pin'],
    Communication: ['Connect VCC to 3.3V', 'Connect GND to ground', 'TX to RX of microcontroller', 'RX to TX of microcontroller'],
    Power: ['Connect positive to VIN/VCC rail', 'Connect negative to GND rail', 'Add 100uF capacitor for stability', 'Check voltage matches all components'],
    Actuator: ['Connect control pin to PWM GPIO', 'Use separate power supply if high current', 'Add flyback diode for motors', 'Connect GND to common ground'],
  }

  let yPos = 35
  components.forEach((comp) => {
    if (yPos > pageHeight - 40) {
      doc.addPage()
      doc.setFillColor(10, 10, 15)
      doc.rect(0, 0, pageWidth, pageHeight, 'F')
      yPos = 20
    }

    const rgb = CATEGORY_COLORS_RGB[comp.category] || [100, 116, 139]
    doc.setFillColor(13, 13, 26)
    doc.rect(20, yPos - 4, pageWidth - 40, 8, 'F')
    doc.setFillColor(...rgb)
    doc.rect(20, yPos - 4, 3, 8, 'F')

    doc.setTextColor(255, 255, 255)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text(comp.name, 26, yPos + 1)
    yPos += 10

    const steps = WIRING[comp.category] || WIRING.Sensor
    steps.forEach(step => {
      doc.setTextColor(148, 163, 184)
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      doc.text('->  ' + step, 25, yPos)
      yPos += 6
    })
    yPos += 5
  })

  // ── PAGE 4 — VALIDATION ─────────────────────────────
  if (validation) {
    doc.addPage()
    doc.setFillColor(10, 10, 15)
    doc.rect(0, 0, pageWidth, pageHeight, 'F')
    doc.setFillColor(99, 102, 241)
    doc.rect(0, 0, pageWidth, 3, 'F')

    doc.setTextColor(255, 255, 255)
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text('AI Validation Report', 20, 22)

    const scoreColor = validation.score >= 80 ? [34, 197, 94] : validation.score >= 60 ? [245, 158, 11] : [239, 68, 68]
    doc.setTextColor(...scoreColor)
    doc.setFontSize(36)
    doc.text(validation.score + '/100', 20, 52)

    doc.setTextColor(200, 200, 200)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    doc.text(validation.verdict || '', 20, 62)

    let vY = 78
    if (validation.issues?.length > 0) {
      doc.setTextColor(239, 68, 68)
      doc.setFontSize(11)
      doc.setFont('helvetica', 'bold')
      doc.text('Issues:', 20, vY)
      vY += 8
      validation.issues.forEach(issue => {
        doc.setTextColor(200, 150, 150)
        doc.setFontSize(9)
        doc.setFont('helvetica', 'normal')
        doc.text('- ' + issue, 25, vY)
        vY += 7
      })
      vY += 5
    }

    if (validation.suggestions?.length > 0) {
      doc.setTextColor(99, 102, 241)
      doc.setFontSize(11)
      doc.setFont('helvetica', 'bold')
      doc.text('Suggestions:', 20, vY)
      vY += 8
      validation.suggestions.forEach(s => {
        doc.setTextColor(165, 180, 252)
        doc.setFontSize(9)
        doc.setFont('helvetica', 'normal')
        doc.text('- ' + s, 25, vY)
        vY += 7
      })
    }
  }

  const fileName = idea.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30)
  doc.save('ProtoMind_Report_' + fileName + '.pdf')
}