export async function generateSpecSheet(idea, components) {
  const componentList = components.map(c =>
    c.name + ' (' + c.category + ')'
  ).join(', ')

  const settings = localStorage.getItem('protomind_settings')
  const model = settings ? (JSON.parse(settings).aiModel || 'llama3.2') : 'llama3.2'
  const ollamaUrl = settings ? (JSON.parse(settings).ollamaUrl || 'http://localhost:11434') : 'http://localhost:11434'

  const response = await fetch(ollamaUrl + '/api/generate', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model,
      prompt: 'You are a professional electronics engineer writing a technical specification document.\n\nPrototype: "' + idea + '"\nComponents: ' + componentList + '\n\nGenerate a complete technical spec sheet. Reply ONLY with this exact JSON:\n\n{"productName": "ProtoMind Sensor Node v1.0", "version": "1.0.0", "date": "2025", "classification": "Prototype / Educational", "overview": "2 sentence technical overview", "electrical": {"supplyVoltage": "5V DC ±5%", "currentConsumption": {"idle": "45mA", "active": "120mA", "peak": "250mA"}, "logicLevel": "5V TTL / 3.3V CMOS", "inputVoltageRange": "4.5V - 5.5V", "maxPinCurrent": "40mA per I/O pin"}, "mechanical": {"dimensions": "68mm x 45mm x 20mm", "weight": "~35g", "pcbLayers": 2, "mountingHoles": 4, "enclosureType": "Open frame / Optional 3D printed case"}, "environmental": {"operatingTemp": "-10°C to 70°C", "storageTemp": "-20°C to 85°C", "humidity": "10% to 90% non-condensing", "ipRating": "IP20 (no enclosure)"}, "performance": {"processingSpeed": "16MHz ATmega328P", "adcResolution": "10-bit", "pwmChannels": 6, "analogInputs": 8, "digitalIO": 22}, "interfaces": [{"name": "I2C", "pins": "A4 (SDA), A5 (SCL)", "speed": "100kHz / 400kHz", "devices": "Up to 127 devices"}, {"name": "SPI", "pins": "D10-D13", "speed": "8MHz max", "devices": "Multiple with CS pins"}], "compliance": ["CE Mark (self-declared)", "RoHS compliant components"], "limitations": ["Not waterproof without enclosure", "No overvoltage protection on I/O pins"], "revision": [{"version": "1.0.0", "date": "2025-01", "changes": "Initial release"}]}',
      stream: false,
    }),
  })

  const data = await response.json()
  const text = data.response
  const jsonMatch = text.match(/\{[\s\S]*\}/)
  if (!jsonMatch) throw new Error('No JSON found')
  return JSON.parse(jsonMatch[0])
}

export function exportSpecSheetMarkdown(spec, idea, components) {
  const lines = [
    '# ' + (spec.productName || idea) + ' — Technical Specification',
    '',
    '**Version:** ' + (spec.version || '1.0.0') + '  ',
    '**Date:** ' + (spec.date || new Date().getFullYear()) + '  ',
    '**Classification:** ' + (spec.classification || 'Prototype') + '  ',
    '**Generated by:** ProtoMind — protomind-ten.vercel.app',
    '',
    '---',
    '',
    '## Overview',
    '',
    spec.overview || '',
    '',
    '## Component List',
    '',
    ...components.map((c, i) => (i + 1) + '. **' + c.name + '** (' + c.category + ')'),
    '',
    '## Electrical Specifications',
    '',
    '| Parameter | Value |',
    '|-----------|-------|',
    '| Supply Voltage | ' + (spec.electrical?.supplyVoltage || 'N/A') + ' |',
    '| Idle Current | ' + (spec.electrical?.currentConsumption?.idle || 'N/A') + ' |',
    '| Active Current | ' + (spec.electrical?.currentConsumption?.active || 'N/A') + ' |',
    '| Peak Current | ' + (spec.electrical?.currentConsumption?.peak || 'N/A') + ' |',
    '| Logic Level | ' + (spec.electrical?.logicLevel || 'N/A') + ' |',
    '| Max Pin Current | ' + (spec.electrical?.maxPinCurrent || 'N/A') + ' |',
    '',
    '## Mechanical Specifications',
    '',
    '| Parameter | Value |',
    '|-----------|-------|',
    '| Dimensions | ' + (spec.mechanical?.dimensions || 'N/A') + ' |',
    '| Weight | ' + (spec.mechanical?.weight || 'N/A') + ' |',
    '| PCB Layers | ' + (spec.mechanical?.pcbLayers || 'N/A') + ' |',
    '| Mounting Holes | ' + (spec.mechanical?.mountingHoles || 'N/A') + ' |',
    '| Enclosure | ' + (spec.mechanical?.enclosureType || 'N/A') + ' |',
    '',
    '## Environmental Specifications',
    '',
    '| Parameter | Value |',
    '|-----------|-------|',
    '| Operating Temperature | ' + (spec.environmental?.operatingTemp || 'N/A') + ' |',
    '| Storage Temperature | ' + (spec.environmental?.storageTemp || 'N/A') + ' |',
    '| Humidity | ' + (spec.environmental?.humidity || 'N/A') + ' |',
    '| IP Rating | ' + (spec.environmental?.ipRating || 'N/A') + ' |',
    '',
    '## Performance',
    '',
    '| Parameter | Value |',
    '|-----------|-------|',
    '| Processing Speed | ' + (spec.performance?.processingSpeed || 'N/A') + ' |',
    '| ADC Resolution | ' + (spec.performance?.adcResolution || 'N/A') + ' |',
    '| PWM Channels | ' + (spec.performance?.pwmChannels || 'N/A') + ' |',
    '',
    '## Communication Interfaces',
    '',
    ...(spec.interfaces || []).flatMap(iface => [
      '### ' + iface.name,
      '- **Pins:** ' + iface.pins,
      '- **Speed:** ' + iface.speed,
      '- **Devices:** ' + iface.devices,
      '',
    ]),
    '## Known Limitations',
    '',
    ...(spec.limitations || []).map(l => '- ' + l),
    '',
    '## Revision History',
    '',
    '| Version | Date | Changes |',
    '|---------|------|---------|',
    ...(spec.revision || []).map(r => '| ' + r.version + ' | ' + r.date + ' | ' + r.changes + ' |'),
    '',
    '---',
    '',
    '*Generated with ProtoMind · protomind-ten.vercel.app*',
  ]
  return lines.join('\n')
}