export async function generateTeamReport(idea, components, options) {
  const componentList = components.map(function(c) {
    return c.name + ' (' + c.category + ')'
  }).join(', ')

  const settings = localStorage.getItem('protomind_settings')
  const model = settings ? (JSON.parse(settings).aiModel || 'llama3.2') : 'llama3.2'
  const ollamaUrl = settings ? (JSON.parse(settings).ollamaUrl || 'http://localhost:11434') : 'http://localhost:11434'

  const prompt = [
    'You are a professional technical project manager.',
    'Generate a comprehensive project status report.',
    'Project: ' + idea,
    'Components: ' + componentList,
    'Team: ' + (options.teamName || 'ProtoMind Team'),
    'Progress: ' + (options.progressPercent || 50) + '% complete',
    'Reply ONLY with valid JSON with exactly these keys:',
    'reportTitle (string),',
    'executiveSummary (string, 3-4 sentences),',
    'projectStatus (string: On Track, At Risk, or Delayed),',
    'completionPercent (number),',
    'sections (array of objects with: title, content, status),',
    'componentDecisions (array of objects with: component, decision, rationale),',
    'challenges (array of objects with: challenge, impact, resolution),',
    'milestones (array of objects with: name, dueDate, status, notes),',
    'budgetStatus (object with: estimated, spent, remaining),',
    'recommendations (array of strings),',
    'nextMeeting (string)',
  ].join('\n')

  const response = await fetch(ollamaUrl + '/api/generate', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ model, prompt, stream: false }),
  })

  const data = await response.json()
  const text = data.response
  const jsonMatch = text.match(/\{[\s\S]*\}/)
  if (!jsonMatch) throw new Error('No JSON found')
  return JSON.parse(jsonMatch[0])
}

export function exportReportAsText(report, idea, options) {
  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  })

  const divider = '='.repeat(60)
  const thinDivider = '-'.repeat(60)

  const lines = [
    divider,
    report.reportTitle || idea,
    'Project Status Report',
    'Date: ' + date,
    'Team: ' + (options.teamName || 'ProtoMind Team'),
    divider,
    '',
    'EXECUTIVE SUMMARY',
    thinDivider,
    report.executiveSummary || '',
    '',
    'PROJECT STATUS: ' + (report.projectStatus || 'In Progress'),
    'COMPLETION: ' + (report.completionPercent || 0) + '%',
    '',
  ]

  if (report.sections && report.sections.length > 0) {
    report.sections.forEach(function(section) {
      lines.push(section.title.toUpperCase())
      lines.push(thinDivider)
      lines.push(section.content || '')
      lines.push('Status: ' + (section.status || 'In Progress'))
      lines.push('')
    })
  }

  if (report.componentDecisions && report.componentDecisions.length > 0) {
    lines.push('COMPONENT DECISIONS')
    lines.push(thinDivider)
    report.componentDecisions.forEach(function(cd) {
      lines.push('Component: ' + cd.component)
      lines.push('Decision: ' + cd.decision)
      lines.push('Rationale: ' + cd.rationale)
      lines.push('')
    })
  }

  if (report.challenges && report.challenges.length > 0) {
    lines.push('CHALLENGES')
    lines.push(thinDivider)
    report.challenges.forEach(function(ch, i) {
      lines.push((i + 1) + '. ' + ch.challenge)
      lines.push('   Impact: ' + ch.impact)
      lines.push('   Resolution: ' + ch.resolution)
      lines.push('')
    })
  }

  if (report.milestones && report.milestones.length > 0) {
    lines.push('MILESTONES')
    lines.push(thinDivider)
    report.milestones.forEach(function(m) {
      lines.push('[' + (m.status || 'Pending') + '] ' + m.name + ' — ' + (m.dueDate || 'TBD'))
      if (m.notes) lines.push('   ' + m.notes)
    })
    lines.push('')
  }

  if (report.recommendations && report.recommendations.length > 0) {
    lines.push('RECOMMENDATIONS')
    lines.push(thinDivider)
    report.recommendations.forEach(function(rec, i) {
      lines.push((i + 1) + '. ' + rec)
    })
    lines.push('')
  }

  lines.push(divider)
  lines.push('Generated by ProtoMind — protomind-ten.vercel.app')
  lines.push(divider)

  return lines.join('\n')
}