export async function generateTestSuite(idea, components) {
  const componentList = components.map(function(c) {
    return c.name + ' (' + c.category + ')'
  }).join(', ')

  const settings = localStorage.getItem('protomind_settings')
  const model = settings ? (JSON.parse(settings).aiModel || 'llama3.2') : 'llama3.2'
  const ollamaUrl = settings ? (JSON.parse(settings).ollamaUrl || 'http://localhost:11434') : 'http://localhost:11434'

  const prompt = [
    'You are an expert electronics QA engineer.',
    'Generate a comprehensive test suite for this prototype.',
    'Prototype: ' + idea,
    'Components: ' + componentList,
    'Reply ONLY with valid JSON with exactly these keys:',
    'suiteName (string),',
    'totalTests (number),',
    'estimatedTime (string),',
    'categories (array of objects with: name, icon, description, tests array of objects with: id, name, description, type, steps array of strings, expectedResult, severity, automated)',
  ].join('\n')

  const response = await fetch(ollamaUrl + '/api/generate', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ model, prompt, stream: false }),
  })

  const data = await response.json()
  const text = data.response
  const jsonMatch = text.match(/\{[\s\S]*\}/)
  if (!jsonMatch) throw new Error('No JSON found')
  return JSON.parse(jsonMatch[0])
}

const RESULTS_KEY = 'protomind_test_results'

export function saveTestResult(suiteId, testId, result) {
  try {
    const raw = localStorage.getItem(RESULTS_KEY)
    const all = raw ? JSON.parse(raw) : {}
    if (!all[suiteId]) all[suiteId] = {}
    all[suiteId][testId] = {
      result,
      testedAt: new Date().toISOString(),
    }
    localStorage.setItem(RESULTS_KEY, JSON.stringify(all))
  } catch {}
}

export function getTestResults(suiteId) {
  try {
    const raw = localStorage.getItem(RESULTS_KEY)
    const all = raw ? JSON.parse(raw) : {}
    return all[suiteId] || {}
  } catch {
    return {}
  }
}

export function clearTestResults(suiteId) {
  try {
    const raw = localStorage.getItem(RESULTS_KEY)
    const all = raw ? JSON.parse(raw) : {}
    delete all[suiteId]
    localStorage.setItem(RESULTS_KEY, JSON.stringify(all))
  } catch {}
}

export function exportTestReport(suite, results, idea) {
  const lines = [
    'TEST REPORT: ' + (suite.suiteName || idea),
    '='.repeat(60),
    'Generated: ' + new Date().toLocaleString(),
    '',
  ]

  let totalPassed = 0
  let totalFailed = 0
  let totalSkipped = 0
  let totalTests = 0

  ;(suite.categories || []).forEach(function(category) {
    lines.push(category.name.toUpperCase())
    lines.push('-'.repeat(40))
    ;(category.tests || []).forEach(function(test) {
      const result = results[test.id]
      const status = result ? result.result : 'not run'
      totalTests++
      if (status === 'pass') totalPassed++
      else if (status === 'fail') totalFailed++
      else totalSkipped++
      lines.push('[' + status.toUpperCase().padEnd(8) + '] ' + test.name)
      if (result && result.testedAt) {
        lines.push('           Tested: ' + new Date(result.testedAt).toLocaleString())
      }
    })
    lines.push('')
  })

  lines.push('='.repeat(60))
  lines.push('SUMMARY')
  lines.push('Total:   ' + totalTests)
  lines.push('Passed:  ' + totalPassed + ' (' + Math.round(totalPassed / Math.max(totalTests, 1) * 100) + '%)')
  lines.push('Failed:  ' + totalFailed)
  lines.push('Skipped: ' + totalSkipped)
  lines.push('')
  lines.push('Generated by ProtoMind — protomind-ten.vercel.app')

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = 'TestReport_' + (idea || 'prototype').replace(/[^a-zA-Z0-9]/g, '_').slice(0, 20) + '.txt'
  link.click()
  URL.revokeObjectURL(url)
}