export async function generateWiringGuide(idea, components) {
  const componentList = components.map(function(c) {
    return c.name + ' (' + c.category + ')'
  }).join(', ')

  const settings = localStorage.getItem('protomind_settings')
  const model = settings ? (JSON.parse(settings).aiModel || 'llama3.2') : 'llama3.2'
  const ollamaUrl = settings ? (JSON.parse(settings).ollamaUrl || 'http://localhost:11434') : 'http://localhost:11434'

  const prompt = [
    'You are an expert electronics wiring instructor.',
    'Generate a detailed step-by-step wiring guide for this prototype.',
    'Prototype: ' + idea,
    'Components: ' + componentList,
    'Reply ONLY with valid JSON with exactly these keys:',
    'title (string),',
    'overview (string, 2 sentences),',
    'toolsNeeded (array of strings),',
    'safetyWarnings (array of strings),',
    'connections (array of objects with: step, fromComponent, fromPin, toComponent, toPin, wireColor, notes),',
    'powerConnections (array of objects with: component, vccPin, gndPin, voltage, notes),',
    'groups (array of objects with: groupName, description, connectionIds array of step numbers),',
    'testingSteps (array of objects with: step, description, expectedResult),',
    'commonMistakes (array of strings),',
    'tips (array of strings)',
  ].join('\n')

  const response = await fetch(ollamaUrl + '/api/generate', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ model, prompt, stream: false }),
  })

  const data = await response.json()
  const text = data.response
  const jsonMatch = text.match(/\{[\s\S]*\}/)
  if (!jsonMatch) throw new Error('No JSON found')
  return JSON.parse(jsonMatch[0])
}

export function exportWiringGuide(guide, idea) {
  const lines = [
    'WIRING GUIDE: ' + (guide.title || idea),
    '='.repeat(60),
    '',
    'OVERVIEW',
    guide.overview || '',
    '',
    'TOOLS NEEDED',
    (guide.toolsNeeded || []).map(function(t) { return '- ' + t }).join('\n'),
    '',
    'SAFETY WARNINGS',
    (guide.safetyWarnings || []).map(function(w) { return '! ' + w }).join('\n'),
    '',
    'POWER CONNECTIONS',
    (guide.powerConnections || []).map(function(p) {
      return p.component + ': VCC=' + p.vccPin + ' GND=' + p.gndPin + ' (' + p.voltage + ')'
    }).join('\n'),
    '',
    'WIRING STEPS',
    (guide.connections || []).map(function(c) {
      return 'Step ' + c.step + ': ' + c.fromComponent + ' [' + c.fromPin + '] → ' + c.toComponent + ' [' + c.toPin + '] (' + (c.wireColor || 'any') + ' wire)'
    }).join('\n'),
    '',
    'TESTING',
    (guide.testingSteps || []).map(function(t) {
      return t.step + '. ' + t.description + '\n   Expected: ' + t.expectedResult
    }).join('\n'),
    '',
    'COMMON MISTAKES',
    (guide.commonMistakes || []).map(function(m) { return '- ' + m }).join('\n'),
    '',
    '---',
    'Generated by ProtoMind — protomind-ten.vercel.app',
  ]

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = 'WiringGuide_' + (idea || 'prototype').replace(/[^a-zA-Z0-9]/g, '_').slice(0, 20) + '.txt'
  link.click()
  URL.revokeObjectURL(url)
}