import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  WidthType,
  ShadingType,
} from 'docx'

function makeHeading(text, level) {
  return new Paragraph({
    text,
    heading: level || HeadingLevel.HEADING_1,
    spacing: { before: 300, after: 150 },
  })
}

function makeParagraph(text, options) {
  return new Paragraph({
    children: [
      new TextRun({
        text: text || '',
        size: 24,
        font: 'Calibri',
        color: options && options.color ? options.color : '000000',
        bold: options && options.bold ? true : false,
      }),
    ],
    spacing: { before: 100, after: 100 },
    alignment: options && options.center ? AlignmentType.CENTER : AlignmentType.LEFT,
  })
}

function makeBullet(text) {
  return new Paragraph({
    children: [new TextRun({ text: '• ' + text, size: 22, font: 'Calibri' })],
    spacing: { before: 60, after: 60 },
    indent: { left: 360 },
  })
}

function makeTableRow(cells, isHeader) {
  return new TableRow({
    children: cells.map(function(cellText) {
      return new TableCell({
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: String(cellText || ''),
                size: 20,
                bold: isHeader || false,
                color: isHeader ? 'FFFFFF' : '333333',
                font: 'Calibri',
              }),
            ],
          }),
        ],
        shading: isHeader ? {
          fill: '6366f1',
          type: ShadingType.CLEAR,
        } : undefined,
        width: { size: 100 / cells.length, type: WidthType.PERCENTAGE },
        margins: { top: 80, bottom: 80, left: 120, right: 120 },
      })
    }),
  })
}

export async function generateWordDoc(idea, components, aiContent) {
  const title = aiContent?.title || idea
  const summary = aiContent?.summary || 'This document describes the prototype design and implementation.'
  const description = aiContent?.description || ''
  const features = aiContent?.features || []
  const challenges = aiContent?.challenges || []
  const recommendations = aiContent?.recommendations || []
  const totalCostMin = components.reduce(function(sum, c) {
    const price = c.estimatedPrice || '$5'
    const num = parseInt(price.match(/\d+/)?.[0] || '5')
    return sum + num
  }, 0)
  const totalCostMax = components.reduce(function(sum, c) {
    const price = c.estimatedPrice || '$15'
    const matches = price.match(/\d+/g) || ['15']
    const num = parseInt(matches[matches.length - 1]) || 15
    return sum + num
  }, 0)

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            children: [new TextRun({ text: '', break: 1 })],
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: '⚡ ProtoMind',
                size: 28,
                bold: true,
                color: '6366f1',
                font: 'Calibri',
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { before: 400, after: 100 },
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: 'Electronics Prototype Report',
                size: 22,
                color: '666666',
                font: 'Calibri',
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 600 },
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: title,
                size: 40,
                bold: true,
                color: '1a1a2e',
                font: 'Calibri',
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { before: 200, after: 200 },
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: 'Generated by ProtoMind  •  protomind-ten.vercel.app',
                size: 18,
                color: '999999',
                font: 'Calibri',
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { before: 100, after: 100 },
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
                size: 18,
                color: '999999',
                font: 'Calibri',
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 800 },
          }),

          makeHeading('1. Executive Summary'),
          makeParagraph(summary),
          makeParagraph(description),

          makeHeading('2. Project Overview'),
          makeParagraph('Prototype: ' + idea),
          makeParagraph('Total Components: ' + components.length),
          makeParagraph('Estimated Cost Range: $' + totalCostMin + ' — $' + totalCostMax + ' USD'),

          makeHeading('3. Features', HeadingLevel.HEADING_2),
          ...(features.length > 0
            ? features.map(function(f) { return makeBullet(f) })
            : [makeParagraph('No features specified.')]
          ),

          makeHeading('4. Component List', HeadingLevel.HEADING_1),
          new Table({
            rows: [
              makeTableRow(['#', 'Component', 'Category', 'Est. Price'], true),
              ...components.map(function(comp, i) {
                return makeTableRow([
                  String(i + 1),
                  comp.name,
                  comp.category,
                  comp.estimatedPrice || 'N/A',
                ])
              }),
            ],
            width: { size: 100, type: WidthType.PERCENTAGE },
          }),

          new Paragraph({ children: [new TextRun({ text: '' })], spacing: { before: 200 } }),

          makeHeading('5. Cost Analysis', HeadingLevel.HEADING_1),
          new Table({
            rows: [
              makeTableRow(['Component', 'Min Cost', 'Max Cost'], true),
              ...components.map(function(comp) {
                const price = comp.estimatedPrice || '$5-15'
                const nums = price.match(/\d+/g) || ['5', '15']
                return makeTableRow([
                  comp.name,
                  '$' + nums[0],
                  '$' + (nums[1] || nums[0]),
                ])
              }),
              makeTableRow(['TOTAL', '$' + totalCostMin, '$' + totalCostMax], true),
            ],
            width: { size: 100, type: WidthType.PERCENTAGE },
          }),

          new Paragraph({ children: [new TextRun({ text: '' })], spacing: { before: 200 } }),

          makeHeading('6. Challenges', HeadingLevel.HEADING_1),
          ...(challenges.length > 0
            ? challenges.map(function(c) { return makeBullet(c) })
            : [makeParagraph('No challenges documented.')]
          ),

          makeHeading('7. Recommendations', HeadingLevel.HEADING_1),
          ...(recommendations.length > 0
            ? recommendations.map(function(r) { return makeBullet(r) })
            : [makeParagraph('No recommendations specified.')]
          ),

          makeHeading('8. Conclusion', HeadingLevel.HEADING_1),
          makeParagraph(
            'This prototype was designed and documented using ProtoMind, an AI-powered electronics prototyping platform. ' +
            'The design incorporates ' + components.length + ' components with an estimated total cost of $' +
            totalCostMin + ' to $' + totalCostMax + ' USD.'
          ),

          new Paragraph({
            children: [
              new TextRun({
                text: '---',
                size: 18,
                color: 'cccccc',
                font: 'Calibri',
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { before: 400 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: 'Generated by ProtoMind — protomind-ten.vercel.app',
                size: 16,
                color: 'aaaaaa',
                font: 'Calibri',
              }),
            ],
            alignment: AlignmentType.CENTER,
          }),
        ],
      },
    ],
  })

  const buffer = await Packer.toBlob(doc)
  return buffer
}