import { useState } from 'react'
import { generateDatasheet, saveDatasheet, getSavedDatasheet } from '../services/datasheetGeneratorService'
import { notify } from '../services/toast'

const PIN_TYPE_STYLES = {
  Power: 'text-red-400 bg-red-950',
  Ground: 'text-slate-400 bg-slate-900',
  Input: 'text-blue-400 bg-blue-950',
  Output: 'text-green-400 bg-green-950',
  'I/O': 'text-yellow-400 bg-yellow-950',
  Communication: 'text-purple-400 bg-purple-950',
}

function DatasheetGenerator({ components }) {
  const [selectedComp, setSelectedComp] = useState(null)
  const [datasheet, setDatasheet] = useState(null)
  const [loading, setLoading] = useState(false)
  const [activeTab, setActiveTab] = useState('specs')
  const [cache, setCache] = useState({})

  function handleSelectComponent(comp) {
    setSelectedComp(comp)
    const saved = getSavedDatasheet(comp.name) || cache[comp.name]
    if (saved) {
      setDatasheet(saved)
    } else {
      setDatasheet(null)
    }
  }

  async function handleGenerate() {
    if (!selectedComp) {
      notify.warning('Select a component first')
      return
    }
    setLoading(true)
    try {
      const data = await generateDatasheet(selectedComp)
      setDatasheet(data)
      saveDatasheet(selectedComp.name, data)
      setCache(function(prev) {
        const next = Object.assign({}, prev)
        next[selectedComp.name] = data
        return next
      })
      setActiveTab('specs')
      notify.success('Datasheet generated for ' + selectedComp.name)
    } catch {
      notify.error('Generation failed — is Ollama running?')
    } finally {
      setLoading(false)
    }
  }

  function handleExport() {
    if (!datasheet) return
    const lines = [
      'DATASHEET: ' + datasheet.name,
      '='.repeat(60),
      'Manufacturer: ' + (datasheet.manufacturer || 'N/A'),
      'Description: ' + (datasheet.description || ''),
      '',
      'KEY SPECIFICATIONS:',
      ...Object.entries(datasheet.keySpecs || {}).map(function(e) {
        return '  ' + e[0] + ': ' + e[1]
      }),
      '',
      'PINOUT:',
      ...((datasheet.pinout || []).map(function(p) {
        return '  Pin ' + p.pin + ' (' + p.name + '): ' + p.description
      })),
      '',
      'ELECTRICAL CHARACTERISTICS:',
      ...((datasheet.electricalCharacteristics || []).map(function(c) {
        return '  ' + c.parameter + ': ' + c.typical + ' ' + c.unit
      })),
      '',
      'ABSOLUTE MAXIMUMS:',
      ...((datasheet.absoluteMaximums || []).map(function(m) {
        return '  ' + m.parameter + ': ' + m.value + ' ' + m.unit
      })),
      '',
      'APPLICATION NOTES:',
      ...((datasheet.applicationNotes || []).map(function(n) { return '  - ' + n })),
      '',
      'Generated by ProtoMind',
    ]
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = (datasheet.name || 'Datasheet').replace(/\s+/g, '_') + '_Datasheet.txt'
    link.click()
    URL.revokeObjectURL(url)
    notify.success('Datasheet exported!')
  }

  const TABS = [
    { id: 'specs', label: '📋 Specs' },
    { id: 'pinout', label: '📌 Pinout' },
    { id: 'electrical', label: '⚡ Electrical' },
    { id: 'notes', label: '📝 Notes' },
  ]

  return (
    <div className="space-y-4">
      {/* Component selector */}
      <div>
        <p className="text-xs text-slate-500 uppercase tracking-wide mb-2">Select Component</p>
        <div className="flex flex-wrap gap-1">
          {components.map(function(comp) {
            const isSel = selectedComp?.name === comp.name
            const hasCache = !!getSavedDatasheet(comp.name) || !!cache[comp.name]
            return (
              <button
                key={comp.name}
                onClick={function() { handleSelectComponent(comp) }}
                className={'text-xs px-3 py-1.5 rounded-xl border transition flex items-center gap-1 ' + (
                  isSel
                    ? 'bg-indigo-600 text-white border-indigo-600'
                    : 'bg-[#13131f] text-slate-400 border-[#2e2e4e] hover:border-indigo-600'
                )}
              >
                <span>{comp.icon}</span>
                <span>{comp.name.split(' ')[0]}</span>
                {hasCache && <span className="text-green-400 text-xs">●</span>}
              </button>
            )
          })}
        </div>
        {components.length === 0 && (
          <p className="text-slate-600 text-xs py-2">Add components to your prototype first</p>
        )}
      </div>

      {selectedComp && (
        <div className="flex gap-2">
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="flex-1 py-2.5 bg-indigo-600 hover:bg-indigo-500 rounded-xl text-xs font-semibold transition disabled:opacity-50"
          >
            {loading ? '📄 Generating...' : '📄 Generate Datasheet'}
          </button>
          {datasheet && (
            <button onClick={handleExport}
              className="px-4 py-2.5 bg-[#1e1e2e] hover:bg-[#2e2e4e] text-slate-300 rounded-xl text-xs transition">
              ⬇️ Export
            </button>
          )}
        </div>
      )}

      {loading && (
        <div className="flex items-center justify-center py-8 gap-3 bg-[#13131f] border border-[#2e2e4e] rounded-xl">
          <div className="w-6 h-6 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
          <p className="text-slate-400 text-sm">Generating datasheet for {selectedComp?.name}...</p>
        </div>
      )}

      {datasheet && !loading && (
        <>
          {/* Header */}
          <div className="bg-[#13131f] border border-[#2e2e4e] rounded-2xl p-5">
            <div className="flex items-center gap-3 mb-2">
              <span className="text-3xl">{selectedComp?.icon || '🔧'}</span>
              <div>
                <p className="text-white font-black text-lg">{datasheet.name}</p>
                <p className="text-slate-500 text-xs">{datasheet.manufacturer}</p>
              </div>
            </div>
            <p className="text-slate-300 text-sm">{datasheet.description}</p>
          </div>

          {/* Tabs */}
          <div className="flex gap-1 bg-[#13131f] rounded-xl p-1 overflow-x-auto">
            {TABS.map(function(tab) {
              return (
                <button key={tab.id}
                  onClick={function() { setActiveTab(tab.id) }}
                  className={'flex-1 py-2 rounded-lg text-xs font-medium transition whitespace-nowrap ' + (
                    activeTab === tab.id ? 'bg-indigo-600 text-white' : 'text-slate-500 hover:text-white'
                  )}>
                  {tab.label}
                </button>
              )
            })}
          </div>

          {activeTab === 'specs' && datasheet.keySpecs && (
            <div className="bg-[#13131f] border border-[#2e2e4e] rounded-xl overflow-hidden">
              <table className="w-full text-xs">
                <thead>
                  <tr className="bg-[#0d0d1a] border-b border-[#2e2e4e]">
                    <th className="text-left px-4 py-2.5 text-slate-500">Parameter</th>
                    <th className="text-left px-4 py-2.5 text-slate-500">Value</th>
                  </tr>
                </thead>
                <tbody>
                  {Object.entries(datasheet.keySpecs).map(function(entry, i) {
                    return (
                      <tr key={i} className={'border-b border-[#1e1e2e] last:border-0 ' + (i % 2 === 0 ? 'bg-[#13131f]' : 'bg-[#0d0d1a]')}>
                        <td className="px-4 py-2.5 text-slate-400 capitalize">{entry[0]}</td>
                        <td className="px-4 py-2.5 text-white font-mono">{entry[1]}</td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          )}

          {activeTab === 'pinout' && (
            <div className="bg-[#13131f] border border-[#2e2e4e] rounded-xl overflow-hidden">
              <table className="w-full text-xs">
                <thead>
                  <tr className="bg-[#0d0d1a] border-b border-[#2e2e4e]">
                    <th className="text-left px-3 py-2.5 text-slate-500">Pin</th>
                    <th className="text-left px-3 py-2.5 text-slate-500">Name</th>
                    <th className="text-left px-3 py-2.5 text-slate-500">Type</th>
                    <th className="text-left px-3 py-2.5 text-slate-500">Description</th>
                  </tr>
                </thead>
                <tbody>
                  {(datasheet.pinout || []).map(function(pin, i) {
                    const pinStyle = PIN_TYPE_STYLES[pin.type] || 'text-slate-400 bg-slate-900'
                    return (
                      <tr key={i} className={'border-b border-[#1e1e2e] last:border-0 ' + (i % 2 === 0 ? 'bg-[#13131f]' : 'bg-[#0d0d1a]')}>
                        <td className="px-3 py-2 text-indigo-400 font-mono font-bold">{pin.pin}</td>
                        <td className="px-3 py-2 text-white font-mono">{pin.name}</td>
                        <td className="px-3 py-2">
                          <span className={'text-xs px-1.5 py-0.5 rounded ' + pinStyle}>{pin.type}</span>
                        </td>
                        <td className="px-3 py-2 text-slate-400">{pin.description}</td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          )}

          {activeTab === 'electrical' && (
            <div className="space-y-3">
              {(datasheet.absoluteMaximums || []).length > 0 && (
                <div className="bg-red-950 border border-red-900 rounded-xl p-4">
                  <p className="text-red-400 text-xs font-semibold mb-2">⚠️ Absolute Maximum Ratings</p>
                  <div className="space-y-1">
                    {datasheet.absoluteMaximums.map(function(m, i) {
                      return (
                        <div key={i} className="flex items-center justify-between text-xs">
                          <span className="text-slate-400">{m.parameter}</span>
                          <span className="text-red-300 font-mono font-bold">{m.value} {m.unit}</span>
                        </div>
                      )
                    })}
                  </div>
                </div>
              )}

              {(datasheet.electricalCharacteristics || []).length > 0 && (
                <div className="bg-[#13131f] border border-[#2e2e4e] rounded-xl overflow-hidden">
                  <table className="w-full text-xs">
                    <thead>
                      <tr className="bg-[#0d0d1a] border-b border-[#2e2e4e]">
                        <th className="text-left px-3 py-2 text-slate-500">Parameter</th>
                        <th className="text-center px-3 py-2 text-slate-500">Min</th>
                        <th className="text-center px-3 py-2 text-slate-500">Typ</th>
                        <th className="text-center px-3 py-2 text-slate-500">Max</th>
                        <th className="text-left px-3 py-2 text-slate-500">Unit</th>
                      </tr>
                    </thead>
                    <tbody>
                      {datasheet.electricalCharacteristics.map(function(c, i) {
                        return (
                          <tr key={i} className={'border-b border-[#1e1e2e] last:border-0 ' + (i % 2 === 0 ? 'bg-[#13131f]' : 'bg-[#0d0d1a]')}>
                            <td className="px-3 py-2 text-slate-400">{c.parameter}</td>
                            <td className="px-3 py-2 text-center text-slate-500 font-mono">{c.min || '—'}</td>
                            <td className="px-3 py-2 text-center text-white font-mono font-bold">{c.typical || '—'}</td>
                            <td className="px-3 py-2 text-center text-slate-500 font-mono">{c.max || '—'}</td>
                            <td className="px-3 py-2 text-slate-500">{c.unit}</td>
                          </tr>
                        )
                      })}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          )}

          {activeTab === 'notes' && (
            <div className="space-y-3">
              {datasheet.typicalApplication && (
                <div className="bg-indigo-950 border border-indigo-900 rounded-xl p-4">
                  <p className="text-indigo-400 text-xs font-semibold mb-2">🔧 Typical Application</p>
                  <p className="text-slate-300 text-sm">{datasheet.typicalApplication}</p>
                </div>
              )}
              {(datasheet.applicationNotes || []).length > 0 && (
                <div className="bg-[#13131f] border border-[#2e2e4e] rounded-xl p-4">
                  <p className="text-slate-500 text-xs font-semibold mb-2">📝 Application Notes</p>
                  <ul className="space-y-2">
                    {datasheet.applicationNotes.map(function(note, i) {
                      return (
                        <li key={i} className="flex items-start gap-2 text-xs">
                          <span className="text-indigo-400 shrink-0">{i + 1}.</span>
                          <p className="text-slate-300">{note}</p>
                        </li>
                      )
                    })}
                  </ul>
                </div>
              )}
            </div>
          )}
        </>
      )}

      {!selectedComp && (
        <div className="text-center py-8 bg-[#13131f] border border-[#2e2e4e] rounded-xl">
          <div className="text-4xl mb-2">📄</div>
          <p className="text-white font-semibold mb-1">Datasheet Generator</p>
          <p className="text-slate-500 text-sm">Select a component to generate a full AI datasheet</p>
        </div>
      )}
    </div>
  )
}

export default DatasheetGenerator