import { useState } from 'react'
import { generateHackathonPack, saveHackathonPack, getHackathonPack } from '../services/hackathonPackService'
import { notify } from '../services/toast'

function HackathonPack({ idea, components }) {
  const [pack, setPack] = useState(getHackathonPack(idea))
  const [loading, setLoading] = useState(false)
  const [activeTab, setActiveTab] = useState('pitch')

  async function handleGenerate() {
    if (components.length === 0) {
      notify.warning('Add components first')
      return
    }
    setLoading(true)
    try {
      const data = await generateHackathonPack(idea, components)
      setPack(data)
      saveHackathonPack(idea, data)
      notify.success('Hackathon pack ready!')
    } catch {
      notify.error('Generation failed — is Ollama running?')
    } finally {
      setLoading(false)
    }
  }

  function handleExport() {
    if (!pack) return
    const lines = [
      '🏆 HACKATHON SUBMISSION PACK',
      '='.repeat(60),
      '',
      'PROJECT: ' + pack.projectTitle,
      'ONE LINER: ' + pack.oneLiner,
      '',
      'PROBLEM:',
      pack.problemStatement,
      '',
      'SOLUTION:',
      pack.solution,
      '',
      'TECH STACK:',
      (pack.techStack || []).map(function(t) { return '  • ' + t }).join('\n'),
      '',
      '24-HOUR TIMELINE:',
      (pack.timeline || []).map(function(t) { return '  Hour ' + t.hour + ': ' + t.task }).join('\n'),
      '',
      'DEMO SCRIPT:',
      pack.demoScript,
      '',
      'UNIQUENESS: ' + pack.uniqueness,
      'IMPACT: ' + pack.impact,
      '',
      'Generated by ProtoMind',
    ]
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = 'HackathonPack.txt'
    link.click()
    URL.revokeObjectURL(url)
    notify.success('Pack exported!')
  }

  const TABS = [
    { id: 'pitch', label: '🎯 Pitch' },
    { id: 'timeline', label: '⏱️ Timeline' },
    { id: 'qa', label: '❓ Judge Q&A' },
    { id: 'team', label: '👥 Team' },
  ]

  return (
    <div className="space-y-4">
      <div className="flex items-start justify-between gap-3">
        <p className="text-slate-400 text-sm">Generate a complete hackathon submission pack with pitch, timeline and Q&A prep</p>
        <button
          onClick={handleGenerate}
          disabled={loading || components.length === 0}
          className="px-5 py-2.5 bg-orange-700 hover:bg-orange-600 rounded-xl text-sm font-semibold transition disabled:opacity-50 shrink-0"
        >
          {loading ? '🏆 Building...' : '🏆 Build Pack'}
        </button>
      </div>

      {loading && (
        <div className="flex items-center justify-center py-8 gap-3 bg-[#13131f] border border-[#2e2e4e] rounded-xl">
          <div className="w-6 h-6 border-2 border-orange-500 border-t-transparent rounded-full animate-spin" />
          <p className="text-slate-400 text-sm">Building hackathon pack...</p>
        </div>
      )}

      {pack && !loading && (
        <>
          {/* Header */}
          <div className="bg-gradient-to-br from-orange-950 to-[#0d0d1a] border border-orange-800 rounded-2xl p-5">
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className="text-orange-400 text-xs font-semibold mb-1">🏆 HACKATHON PACK</p>
                <h3 className="text-white font-black text-xl">{pack.projectTitle}</h3>
                <p className="text-orange-300 text-sm italic mt-1">"{pack.oneLiner}"</p>
              </div>
              <button onClick={handleExport}
                className="px-3 py-2 bg-orange-900 hover:bg-orange-800 text-orange-300 rounded-xl text-xs transition shrink-0">
                ⬇️ Export
              </button>
            </div>
          </div>

          {/* Tabs */}
          <div className="flex gap-1 bg-[#13131f] rounded-xl p-1 overflow-x-auto">
            {TABS.map(function(tab) {
              return (
                <button key={tab.id}
                  onClick={function() { setActiveTab(tab.id) }}
                  className={'flex-1 py-2 rounded-lg text-xs font-medium transition whitespace-nowrap ' + (
                    activeTab === tab.id ? 'bg-orange-700 text-white' : 'text-slate-500 hover:text-white'
                  )}>
                  {tab.label}
                </button>
              )
            })}
          </div>

          {activeTab === 'pitch' && (
            <div className="space-y-3">
              {[
                { label: '❗ Problem', value: pack.problemStatement },
                { label: '💡 Solution', value: pack.solution },
                { label: '⭐ Uniqueness', value: pack.uniqueness },
                { label: '🌍 Impact', value: pack.impact },
              ].map(function(section) {
                return (
                  <div key={section.label} className="bg-[#13131f] border border-[#2e2e4e] rounded-xl p-4">
                    <p className="text-orange-400 text-xs font-semibold mb-1">{section.label}</p>
                    <p className="text-white text-sm">{section.value}</p>
                  </div>
                )
              })}

              {pack.techStack && pack.techStack.length > 0 && (
                <div className="bg-[#13131f] border border-[#2e2e4e] rounded-xl p-4">
                  <p className="text-orange-400 text-xs font-semibold mb-2">🔧 Tech Stack</p>
                  <div className="flex flex-wrap gap-1">
                    {pack.techStack.map(function(tech, i) {
                      return (
                        <span key={i} className="text-xs bg-[#0d0d1a] border border-[#2e2e4e] text-slate-300 px-2 py-0.5 rounded-full">
                          {tech}
                        </span>
                      )
                    })}
                  </div>
                </div>
              )}

              {pack.demoScript && (
                <div className="bg-orange-950 border border-orange-800 rounded-xl p-4">
                  <p className="text-orange-400 text-xs font-semibold mb-2">🎬 30-Second Demo Script</p>
                  <p className="text-slate-300 text-sm leading-relaxed">{pack.demoScript}</p>
                </div>
              )}
            </div>
          )}

          {activeTab === 'timeline' && (
            <div className="space-y-2">
              {(pack.timeline || []).map(function(item, i) {
                const isEarly = item.hour <= 8
                const isMid = item.hour > 8 && item.hour <= 16
                const color = isEarly ? '#22c55e' : isMid ? '#f59e0b' : '#ef4444'
                return (
                  <div key={i} className="flex items-center gap-3 bg-[#13131f] border border-[#2e2e4e] rounded-xl p-3">
                    <div className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0"
                      style={{ backgroundColor: color + '20', border: '2px solid ' + color + '40' }}>
                      <p className="text-xs font-black" style={{ color }}>H{item.hour}</p>
                    </div>
                    <p className="text-slate-300 text-sm">{item.task}</p>
                  </div>
                )
              })}
            </div>
          )}

          {activeTab === 'qa' && (
            <div className="space-y-3">
              {(pack.judgeQuestions || []).map(function(qa, i) {
                return (
                  <div key={i} className="bg-[#13131f] border border-[#2e2e4e] rounded-xl p-4">
                    <p className="text-orange-400 text-sm font-semibold mb-2">❓ {qa.question}</p>
                    <p className="text-slate-300 text-sm">{qa.answer}</p>
                  </div>
                )
              })}
            </div>
          )}

          {activeTab === 'team' && (
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {(pack.teamRoles || []).map(function(role, i) {
                const colors = ['#6366f1', '#0ea5e9', '#22c55e', '#f59e0b', '#a855f7']
                const color = colors[i % colors.length]
                return (
                  <div key={i} className="rounded-xl border p-4"
                    style={{ backgroundColor: color + '10', borderColor: color + '30' }}>
                    <p className="font-bold text-sm mb-2" style={{ color }}>{role.role}</p>
                    <ul className="space-y-1">
                      {(role.responsibilities || []).map(function(r, j) {
                        return (
                          <li key={j} className="text-slate-400 text-xs flex items-start gap-1">
                            <span style={{ color }} className="shrink-0">→</span> {r}
                          </li>
                        )
                      })}
                    </ul>
                  </div>
                )
              })}
            </div>
          )}

          <button onClick={handleGenerate}
            className="w-full py-2 bg-[#1e1e2e] hover:bg-[#2e2e4e] text-slate-400 rounded-xl text-xs transition">
            ↺ Regenerate Pack
          </button>
        </>
      )}

      {!pack && !loading && (
        <div className="text-center py-8 bg-[#13131f] border border-[#2e2e4e] rounded-xl">
          <div className="text-4xl mb-2">🏆</div>
          <p className="text-white font-semibold mb-1">Hackathon Pack Generator</p>
          <p className="text-slate-500 text-sm">Build a complete submission pack — pitch, timeline, Q&A and team roles</p>
        </div>
      )}
    </div>
  )
}

export default HackathonPack