import { useState } from 'react'
import { generatePCBLayout } from '../services/pcbPlanner'
import { notify } from '../services/toast'

const ZONE_COLORS = {
  center: '#6366f1',
  top: '#0ea5e9',
  bottom: '#22c55e',
  left: '#f59e0b',
  right: '#a855f7',
  'top-left': '#ef4444',
  'top-right': '#0ea5e9',
  'bottom-left': '#22c55e',
  'bottom-right': '#f59e0b',
}

const LAYER_COLORS = {
  top: '#ef4444',
  bottom: '#0ea5e9',
  inner: '#22c55e',
}

function PCBVisualizer({ layout }) {
  if (!layout) return null

  const { boardSize, placement } = layout
  const scaleX = 300 / (boardSize?.width || 80)
  const scaleY = 200 / (boardSize?.height || 60)

  return (
    <div className="bg-[#0a1f0a] border border-green-900 rounded-xl overflow-hidden p-4">
      <p className="text-green-400 text-xs font-semibold mb-2 uppercase tracking-wide">
        PCB Top View — {boardSize?.width || 80}mm × {boardSize?.height || 60}mm
      </p>
      <div
        className="relative rounded-lg overflow-hidden"
        style={{ width: '300px', height: '200px', backgroundColor: '#0f3d0f', border: '2px solid #1a5c1a' }}
      >
        {/* Grid lines */}
        {[1, 2, 3, 4].map(i => (
          <div key={'h' + i} className="absolute w-full" style={{ top: (i * 20) + '%', height: '1px', backgroundColor: 'rgba(0,255,0,0.05)' }} />
        ))}
        {[1, 2, 3, 4].map(i => (
          <div key={'v' + i} className="absolute h-full" style={{ left: (i * 20) + '%', width: '1px', backgroundColor: 'rgba(0,255,0,0.05)' }} />
        ))}

        {/* Mounting holes */}
        {layout.mountingHoles >= 4 && (
          <>
            {[[5, 5], [295, 5], [5, 195], [295, 195]].map(([x, y], i) => (
              <div
                key={i}
                className="absolute w-4 h-4 rounded-full border-2 border-green-700 bg-[#0a1f0a]"
                style={{ left: x - 8, top: y - 8 }}
              />
            ))}
          </>
        )}

        {/* Components */}
        {placement?.map((comp, i) => {
          const x = ((comp.x || 40) / (boardSize?.width || 80)) * 300
          const y = ((comp.y || 30) / (boardSize?.height || 60)) * 200
          const color = ZONE_COLORS[comp.zone] || '#6366f1'
          return (
            <div
              key={i}
              className="absolute flex flex-col items-center"
              style={{ left: x - 20, top: y - 14 }}
              title={comp.component + '\n' + comp.notes}
            >
              <div
                className="w-10 h-6 rounded flex items-center justify-center text-xs font-bold"
                style={{ backgroundColor: color + '30', border: '1px solid ' + color, color }}
              >
                {i + 1}
              </div>
            </div>
          )
        })}

        {/* Edge connector indicator */}
        {layout.connectors?.map((conn, i) => (
          conn.position === 'edge' && (
            <div
              key={i}
              className="absolute right-0 top-1/2 -translate-y-1/2 w-3 h-8 bg-yellow-600 rounded-l"
              title={conn.type + ': ' + conn.purpose}
            />
          )
        ))}
      </div>

      {/* Legend */}
      <div className="flex flex-wrap gap-2 mt-3">
        {placement?.slice(0, 6).map((comp, i) => (
          <div key={i} className="flex items-center gap-1 text-xs">
            <div
              className="w-4 h-4 rounded flex items-center justify-center text-xs font-bold"
              style={{
                backgroundColor: (ZONE_COLORS[comp.zone] || '#6366f1') + '30',
                border: '1px solid ' + (ZONE_COLORS[comp.zone] || '#6366f1'),
                color: ZONE_COLORS[comp.zone] || '#6366f1',
              }}
            >
              {i + 1}
            </div>
            <span className="text-slate-400 truncate max-w-20">{comp.component?.split(' ')[0]}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

function PCBPlanner({ idea, components }) {
  const [layout, setLayout] = useState(null)
  const [loading, setLoading] = useState(false)
  const [activeTab, setActiveTab] = useState('visual')

  async function handleGenerate() {
    setLoading(true)
    setLayout(null)
    try {
      const data = await generatePCBLayout(idea, components)
      setLayout(data)
      notify.success('PCB layout generated!')
    } catch {
      notify.error('PCB generation failed — is Ollama running?')
    } finally {
      setLoading(false)
    }
  }

  function exportKiCad() {
    if (!layout) return
    const lines = [
      '(kicad_pcb (version 20221018)',
      '  (general',
      '    (thickness 1.6)',
      '  )',
      '  (paper "A4")',
      '  ; Generated by ProtoMind',
      '  ; Idea: ' + idea,
      '  ; Components: ' + components.map(c => c.name).join(', '),
      ')',
    ]
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = 'ProtoMind_PCB.kicad_pcb'
    link.click()
    URL.revokeObjectURL(url)
    notify.success('KiCad file exported!')
  }

  const TABS = [
    { id: 'visual', label: '🖥️ Visual' },
    { id: 'placement', label: '📍 Placement' },
    { id: 'traces', label: '⚡ Traces' },
    { id: 'rules', label: '📋 Rules' },
    { id: 'cost', label: '💰 Cost' },
  ]

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-start">
        <p className="text-slate-400 text-sm">
          AI generates a PCB component placement guide and trace routing plan
        </p>
        <button
          onClick={handleGenerate}
          disabled={loading}
          className="px-5 py-2.5 bg-green-700 hover:bg-green-600 rounded-xl text-sm font-semibold transition disabled:opacity-50 shrink-0 ml-4"
        >
          {loading ? '🖥️ Planning...' : '🖥️ Generate PCB Layout'}
        </button>
      </div>

      {loading && (
        <div className="flex items-center justify-center py-12 gap-3 bg-[#13131f] border border-[#2e2e4e] rounded-xl">
          <div className="w-6 h-6 border-2 border-green-500 border-t-transparent rounded-full animate-spin" />
          <p className="text-slate-400 text-sm">AI is designing your PCB layout...</p>
        </div>
      )}

      {layout && !loading && (
        <>
          {/* Board summary */}
          <div className="grid grid-cols-4 gap-3">
            {[
              { label: 'Board Size', value: (layout.boardSize?.width || '?') + '×' + (layout.boardSize?.height || '?') + 'mm', icon: '📐' },
              { label: 'Layers', value: layout.layers || 2, icon: '📚' },
              { label: 'Components', value: layout.placement?.length || 0, icon: '🔧' },
              { label: 'Traces', value: layout.traces?.length || 0, icon: '⚡' },
            ].map(item => (
              <div key={item.label} className="bg-[#13131f] border border-[#2e2e4e] rounded-xl p-3 text-center">
                <p className="text-lg mb-1">{item.icon}</p>
                <p className="text-white font-bold text-sm">{item.value}</p>
                <p className="text-slate-600 text-xs">{item.label}</p>
              </div>
            ))}
          </div>

          {/* Tabs */}
          <div className="flex gap-1 bg-[#13131f] rounded-xl p-1 overflow-x-auto">
            {TABS.map(tab => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`flex-1 py-2 rounded-lg text-xs font-medium transition whitespace-nowrap ${
                  activeTab === tab.id ? 'bg-indigo-600 text-white' : 'text-slate-500 hover:text-white'
                }`}
              >
                {tab.label}
              </button>
            ))}
          </div>

          {/* Visual tab */}
          {activeTab === 'visual' && (
            <div className="space-y-3">
              <PCBVisualizer layout={layout} />
              <button
                onClick={exportKiCad}
                className="w-full py-2.5 bg-[#13131f] hover:bg-[#1e1e2e] border border-[#2e2e4e] text-slate-300 rounded-xl text-xs transition"
              >
                📁 Export KiCad File (.kicad_pcb)
              </button>
            </div>
          )}

          {/* Placement tab */}
          {activeTab === 'placement' && (
            <div className="space-y-2">
              {layout.placement?.map((comp, i) => (
                <div key={i} className="bg-[#13131f] border border-[#2e2e4e] rounded-xl p-4">
                  <div className="flex items-start gap-3">
                    <div
                      className="w-8 h-8 rounded-lg flex items-center justify-center text-xs font-bold shrink-0"
                      style={{
                        backgroundColor: (ZONE_COLORS[comp.zone] || '#6366f1') + '20',
                        color: ZONE_COLORS[comp.zone] || '#6366f1',
                        border: '1px solid ' + (ZONE_COLORS[comp.zone] || '#6366f1') + '40',
                      }}
                    >
                      {i + 1}
                    </div>
                    <div className="flex-1">
                      <p className="text-white text-sm font-semibold">{comp.component}</p>
                      <div className="flex gap-3 mt-1 text-xs text-slate-500 flex-wrap">
                        <span>Zone: <span className="text-slate-300">{comp.zone}</span></span>
                        <span>X: <span className="text-slate-300">{comp.x}mm</span></span>
                        <span>Y: <span className="text-slate-300">{comp.y}mm</span></span>
                        {comp.rotation !== 0 && <span>Rotation: <span className="text-slate-300">{comp.rotation}°</span></span>}
                      </div>
                      {comp.notes && <p className="text-slate-400 text-xs mt-1">{comp.notes}</p>}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Traces tab */}
          {activeTab === 'traces' && (
            <div className="space-y-2">
              {layout.powerPlane && (
                <div className="bg-[#13131f] border border-yellow-900 rounded-xl p-3 mb-3">
                  <p className="text-yellow-400 text-xs font-semibold mb-1">⚡ Power Planes</p>
                  <p className="text-slate-300 text-xs">{layout.powerPlane.positive}</p>
                  <p className="text-slate-300 text-xs">{layout.powerPlane.ground}</p>
                </div>
              )}
              {layout.traces?.map((trace, i) => (
                <div key={i} className="bg-[#13131f] border border-[#2e2e4e] rounded-xl p-3">
                  <div className="flex items-center gap-2 mb-1">
                    <div
                      className="w-3 h-3 rounded-full shrink-0"
                      style={{ backgroundColor: LAYER_COLORS[trace.layer] || '#6366f1' }}
                    />
                    <span className="text-xs font-mono" style={{ color: LAYER_COLORS[trace.layer] || '#6366f1' }}>
                      {trace.layer} layer
                    </span>
                    <span className="text-slate-600 text-xs">{trace.width}</span>
                  </div>
                  <p className="text-white text-xs">
                    <span className="text-indigo-400">{trace.from}</span>
                    <span className="text-slate-500 mx-2">→</span>
                    <span className="text-green-400">{trace.to}</span>
                  </p>
                  {trace.notes && <p className="text-slate-500 text-xs mt-1">{trace.notes}</p>}
                </div>
              ))}
            </div>
          )}

          {/* Rules tab */}
          {activeTab === 'rules' && (
            <div className="bg-[#13131f] border border-[#2e2e4e] rounded-xl p-4">
              <h4 className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-3">Design Rules</h4>
              <ul className="space-y-2">
                {layout.designRules?.map((rule, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm">
                    <span className="text-indigo-400 shrink-0 text-xs mt-1">{i + 1}.</span>
                    <p className="text-slate-300">{rule}</p>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Cost tab */}
          {activeTab === 'cost' && layout.estimatedCost && (
            <div className="space-y-3">
              <div className="bg-emerald-950 border border-emerald-900 rounded-xl p-4">
                <p className="text-emerald-400 text-xs font-semibold uppercase tracking-wide mb-2">PCB Fabrication</p>
                <p className="text-white text-sm">{layout.estimatedCost.pcbFab}</p>
              </div>
              <div className="bg-[#13131f] border border-[#2e2e4e] rounded-xl p-4">
                <p className="text-slate-400 text-xs font-semibold uppercase tracking-wide mb-2">Assembly</p>
                <p className="text-white text-sm">{layout.estimatedCost.assembly}</p>
              </div>
              <div className="bg-indigo-950 border border-indigo-900 rounded-xl p-4">
                <p className="text-indigo-400 text-xs font-semibold mb-1">💡 Recommended Services</p>
                <div className="space-y-1 text-xs text-slate-300">
                  <p>• <span className="text-white">JLCPCB</span> — jlcpcb.com — cheapest fab service</p>
                  <p>• <span className="text-white">PCBWay</span> — pcbway.com — great quality</p>
                  <p>• <span className="text-white">OSHPark</span> — oshpark.com — purple boards</p>
                </div>
              </div>
            </div>
          )}
        </>
      )}

      {!layout && !loading && (
        <div className="text-center py-10 bg-[#13131f] border border-[#2e2e4e] rounded-xl">
          <div className="text-5xl mb-3">🖥️</div>
          <p className="text-white font-semibold mb-1">PCB Layout Planner</p>
          <p className="text-slate-500 text-sm mb-4">AI designs component placement and trace routing</p>
          <div className="flex justify-center gap-4 text-xs text-slate-600">
            <span>✓ Component placement</span>
            <span>✓ Trace routing</span>
            <span>✓ KiCad export</span>
          </div>
        </div>
      )}
    </div>
  )
}

export default PCBPlanner